### ISSUE TITLE
Sample Pictures of UI

### ISSUE THREAD

**Issue by oxbown** [bareboat-necessities/bbn-m5stack-tough#10]
Can you post some pictures of the UI of BBN on M5Stack?
Nice project!!!

**Comment by mgrouch** [comment]
I will add pictures after the release. Meantime if you are interested and if you
have m5stack tough you can compile, install and see all screens and you'd be able to test and contribute with bug reports.

**Comment by oxbown** [comment]
I purchase an M5stack tough in Mouser, when it arrives I´ll test the code and I´ll give you feedback.

**Comment by mgrouch** [comment]
I’ve added some screenshots 

https://github.com/bareboat-necessities/bbn-m5stack-tough/blob/main/screenshots/VIEW.md
