### ISSUE TITLE
Improve network port entry

### ISSUE THREAD

**Issue by Djarid** [bareboat-necessities/bbn-m5stack-tough#29]
Changing the port of a service can be a significant burden.
Holding the `+` or `-` for in over an hour to change a port by 10,000 is simply not workable.
Perhaps have left and right navigation buttons for changing the magnitude being edited in the similar to combination lock entry.

**Comment by mgrouch** [comment]
You probably didn’t notice but it acts as encoder. You can move left and right and edit each digit individually

**Comment by Djarid** [comment]
hmm, I'll give it another go. I had assumed that as the last digit was
highlighted but couldn't get it working. I'll blame my large fingers
