### ISSUE TITLE
Set addresses in ino or in Preferences.h

### ISSUE THREAD

**Issue by hans-martijn** [bareboat-necessities/bbn-m5stack-tough#30]
Would it be possible to put all addresses and wifi ap's + passwords in the ino file or in a Preferences.h file? That would make installing more than one very easy, since the on-screen buttons are really tiny.

I already have two, I'll probably buy more, since I have more steering stands.

Thanks!

-Hans

**Comment by mgrouch** [comment]
Yes sure. You can just initialize variables holding WiFi name and password to whatever you want in the code.

**Comment by hans-martijn** [comment]
Where would I do that, and can I also add signalk, Venus etc. with ip and port in the code?

-Hans

**Comment by mgrouch** [comment]
WiFi name and password variables are defined right in .ino file. Connections are defined in bbn-m5stack-tough/bbn_m5tough_active_boat/ui_mem_cpu_net_stat.h at main · bareboat-necessities/bbn-m5stack-toughgithub.comSent from my iPhoneOn 28 Oct 2023, at 11:24, Hans-Martijn ***@***.***> wrote:﻿
Where would I do that, and can I also add signalk, Venus etc. with ip and port in the code?
-Hans

**Comment by hans-martijn** [comment]
Thanks Mikhail, I'll try to manage that in the code!
